name: flake8 Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          flake8-version: "6.1.0"
          path: ""
          args: "--max-doc-length=80 --ignore=B950,D105,DOC301,E203,E501,W503 --require-plugins=flake8-black,flake8-bugbear,flake8-docstrings,flake8-isort,pep8-naming,pycodestyle,pydoclint,pyflakes"
          max-line-length: "100"
          update-pip: "true"
          plugins: "flake8-black==0.3.6 flake8-bugbear==23.12.2 flake8-docstrings==1.7.0 flake8-isort==6.1.1 pep8-naming==0.13.3 pycodestyle==2.11.1 pydoclint==0.3.8 pyflakes==3.1.0"
